### ISSUE TITLE
Refreshing the page suddenly redirects to landing

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-platform#540]
https://github.com/user-attachments/assets/cfe1a78f-1efc-4326-93c3-81c8a3cceb16

**Comment by kittybest** [comment]
It's because of this:
https://github.com/privacy-scaling-explorations/maci-platform/blob/52a14bf72fbb2e980512e835940282ef602513bf/packages/interface/src/pages/rounds/%5BpollId%5D/ballot/index.tsx#L166-L170

So when refreshing page, the `address` or `isConnecting` is not yet confirmed, that's why it push to the homepage.

The solution for this might be
1. not directly redirect to the homepage, but display a button to inform them this page require the user to connect to their wallet first
2. sleep for 5 seconds then check if there's `address` and `isConnecting`
